# Generated by Django 2.0.7 on 2018-09-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsA',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('main_category', models.CharField(max_length=250)),
                ('main_category_fr', models.CharField(max_length=250)),
                ('image_small_url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Nom de la classe',
                'db_table': 'products_A',
                'managed': False,
            },
        ),
    ]
