# Generated by Django 2.0.7 on 2018-10-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsA',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('main_category', models.CharField(max_length=250)),
                ('main_category_fr', models.CharField(max_length=250)),
                ('image_small_url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Produits A',
                'db_table': 'products_A',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('code', models.BigIntegerField()),
                ('url', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('main_category', models.CharField(max_length=250)),
                ('main_category_fr', models.CharField(max_length=250)),
                ('image_small_url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Produits utilisateur',
                'db_table': 'user_products',
                'managed': True,
            },
        ),
    ]
