# Generated by Django 2.0.7 on 2018-09-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitution_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('code', models.BigIntegerField()),
                ('url', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('main_category', models.CharField(max_length=250)),
                ('main_category_fr', models.CharField(max_length=250)),
                ('image_small_url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Produits utilisateur',
                'db_table': 'user_products',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='productsa',
            options={'managed': False, 'verbose_name': 'Produits A'},
        ),
    ]
