# Generated by Django 2.0.7 on 2018-10-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitution_app', '0003_auto_20181003_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsa',
            options={'managed': False, 'verbose_name': 'Produits A'},
        ),
        migrations.AlterModelOptions(
            name='userproducts',
            options={'managed': False, 'verbose_name': 'Produits utilisateur'},
        ),
    ]
